# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/api/grpc/common.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='core/api/grpc/common.proto',
  package='common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1a\x63ore/api/grpc/common.proto\x12\x06\x63ommon\"g\n\x0c\x43onfigOption\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x0e\n\x06select\x18\x05 \x03(\t\x12\r\n\x05group\x18\x06 \x01(\t\"\x85\x01\n\x0cMappedConfig\x12\x30\n\x06\x63onfig\x18\x01 \x03(\x0b\x32 .common.MappedConfig.ConfigEntry\x1a\x43\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.common.ConfigOption:\x02\x38\x01\x62\x06proto3'
)




_CONFIGOPTION = _descriptor.Descriptor(
  name='ConfigOption',
  full_name='common.ConfigOption',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='common.ConfigOption.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='common.ConfigOption.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='common.ConfigOption.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='common.ConfigOption.type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='select', full_name='common.ConfigOption.select', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group', full_name='common.ConfigOption.group', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=141,
)


_MAPPEDCONFIG_CONFIGENTRY = _descriptor.Descriptor(
  name='ConfigEntry',
  full_name='common.MappedConfig.ConfigEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='common.MappedConfig.ConfigEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='common.MappedConfig.ConfigEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=277,
)

_MAPPEDCONFIG = _descriptor.Descriptor(
  name='MappedConfig',
  full_name='common.MappedConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='common.MappedConfig.config', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MAPPEDCONFIG_CONFIGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=277,
)

_MAPPEDCONFIG_CONFIGENTRY.fields_by_name['value'].message_type = _CONFIGOPTION
_MAPPEDCONFIG_CONFIGENTRY.containing_type = _MAPPEDCONFIG
_MAPPEDCONFIG.fields_by_name['config'].message_type = _MAPPEDCONFIG_CONFIGENTRY
DESCRIPTOR.message_types_by_name['ConfigOption'] = _CONFIGOPTION
DESCRIPTOR.message_types_by_name['MappedConfig'] = _MAPPEDCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigOption = _reflection.GeneratedProtocolMessageType('ConfigOption', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGOPTION,
  '__module__' : 'core.api.grpc.common_pb2'
  # @@protoc_insertion_point(class_scope:common.ConfigOption)
  })
_sym_db.RegisterMessage(ConfigOption)

MappedConfig = _reflection.GeneratedProtocolMessageType('MappedConfig', (_message.Message,), {

  'ConfigEntry' : _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _MAPPEDCONFIG_CONFIGENTRY,
    '__module__' : 'core.api.grpc.common_pb2'
    # @@protoc_insertion_point(class_scope:common.MappedConfig.ConfigEntry)
    })
  ,
  'DESCRIPTOR' : _MAPPEDCONFIG,
  '__module__' : 'core.api.grpc.common_pb2'
  # @@protoc_insertion_point(class_scope:common.MappedConfig)
  })
_sym_db.RegisterMessage(MappedConfig)
_sym_db.RegisterMessage(MappedConfig.ConfigEntry)


_MAPPEDCONFIG_CONFIGENTRY._options = None
# @@protoc_insertion_point(module_scope)
