# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/api/grpc/mobility.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core.api.grpc import common_pb2 as core_dot_api_dot_grpc_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='core/api/grpc/mobility.proto',
  package='mobility',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1c\x63ore/api/grpc/mobility.proto\x12\x08mobility\x1a\x1a\x63ore/api/grpc/common.proto\"8\n\x0eMobilityAction\"&\n\x04\x45num\x12\t\n\x05START\x10\x00\x12\t\n\x05PAUSE\x10\x01\x12\x08\n\x04STOP\x10\x02\"\x86\x01\n\x0eMobilityConfig\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x34\n\x06\x63onfig\x18\x02 \x03(\x0b\x32$.mobility.MobilityConfig.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"/\n\x19GetMobilityConfigsRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\"\xa6\x01\n\x1aGetMobilityConfigsResponse\x12\x42\n\x07\x63onfigs\x18\x01 \x03(\x0b\x32\x31.mobility.GetMobilityConfigsResponse.ConfigsEntry\x1a\x44\n\x0c\x43onfigsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.common.MappedConfig:\x02\x38\x01\"?\n\x18GetMobilityConfigRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\"\xa1\x01\n\x19GetMobilityConfigResponse\x12?\n\x06\x63onfig\x18\x01 \x03(\x0b\x32/.mobility.GetMobilityConfigResponse.ConfigEntry\x1a\x43\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.common.ConfigOption:\x02\x38\x01\"a\n\x18SetMobilityConfigRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x31\n\x0fmobility_config\x18\x02 \x01(\x0b\x32\x18.mobility.MobilityConfig\"+\n\x19SetMobilityConfigResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\"k\n\x15MobilityActionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\x12-\n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32\x1d.mobility.MobilityAction.Enum\"(\n\x16MobilityActionResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x62\x06proto3'
  ,
  dependencies=[core_dot_api_dot_grpc_dot_common__pb2.DESCRIPTOR,])



_MOBILITYACTION_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='mobility.MobilityAction.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAUSE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=88,
  serialized_end=126,
)
_sym_db.RegisterEnumDescriptor(_MOBILITYACTION_ENUM)


_MOBILITYACTION = _descriptor.Descriptor(
  name='MobilityAction',
  full_name='mobility.MobilityAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MOBILITYACTION_ENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=126,
)


_MOBILITYCONFIG_CONFIGENTRY = _descriptor.Descriptor(
  name='ConfigEntry',
  full_name='mobility.MobilityConfig.ConfigEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mobility.MobilityConfig.ConfigEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='mobility.MobilityConfig.ConfigEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=263,
)

_MOBILITYCONFIG = _descriptor.Descriptor(
  name='MobilityConfig',
  full_name='mobility.MobilityConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='mobility.MobilityConfig.node_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='mobility.MobilityConfig.config', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MOBILITYCONFIG_CONFIGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=263,
)


_GETMOBILITYCONFIGSREQUEST = _descriptor.Descriptor(
  name='GetMobilityConfigsRequest',
  full_name='mobility.GetMobilityConfigsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='mobility.GetMobilityConfigsRequest.session_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=312,
)


_GETMOBILITYCONFIGSRESPONSE_CONFIGSENTRY = _descriptor.Descriptor(
  name='ConfigsEntry',
  full_name='mobility.GetMobilityConfigsResponse.ConfigsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mobility.GetMobilityConfigsResponse.ConfigsEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='mobility.GetMobilityConfigsResponse.ConfigsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=481,
)

_GETMOBILITYCONFIGSRESPONSE = _descriptor.Descriptor(
  name='GetMobilityConfigsResponse',
  full_name='mobility.GetMobilityConfigsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='configs', full_name='mobility.GetMobilityConfigsResponse.configs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETMOBILITYCONFIGSRESPONSE_CONFIGSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=481,
)


_GETMOBILITYCONFIGREQUEST = _descriptor.Descriptor(
  name='GetMobilityConfigRequest',
  full_name='mobility.GetMobilityConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='mobility.GetMobilityConfigRequest.session_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='mobility.GetMobilityConfigRequest.node_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=546,
)


_GETMOBILITYCONFIGRESPONSE_CONFIGENTRY = _descriptor.Descriptor(
  name='ConfigEntry',
  full_name='mobility.GetMobilityConfigResponse.ConfigEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mobility.GetMobilityConfigResponse.ConfigEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='mobility.GetMobilityConfigResponse.ConfigEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=643,
  serialized_end=710,
)

_GETMOBILITYCONFIGRESPONSE = _descriptor.Descriptor(
  name='GetMobilityConfigResponse',
  full_name='mobility.GetMobilityConfigResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='mobility.GetMobilityConfigResponse.config', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETMOBILITYCONFIGRESPONSE_CONFIGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=549,
  serialized_end=710,
)


_SETMOBILITYCONFIGREQUEST = _descriptor.Descriptor(
  name='SetMobilityConfigRequest',
  full_name='mobility.SetMobilityConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='mobility.SetMobilityConfigRequest.session_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mobility_config', full_name='mobility.SetMobilityConfigRequest.mobility_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=712,
  serialized_end=809,
)


_SETMOBILITYCONFIGRESPONSE = _descriptor.Descriptor(
  name='SetMobilityConfigResponse',
  full_name='mobility.SetMobilityConfigResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='mobility.SetMobilityConfigResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=811,
  serialized_end=854,
)


_MOBILITYACTIONREQUEST = _descriptor.Descriptor(
  name='MobilityActionRequest',
  full_name='mobility.MobilityActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='mobility.MobilityActionRequest.session_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='mobility.MobilityActionRequest.node_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='mobility.MobilityActionRequest.action', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=856,
  serialized_end=963,
)


_MOBILITYACTIONRESPONSE = _descriptor.Descriptor(
  name='MobilityActionResponse',
  full_name='mobility.MobilityActionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='mobility.MobilityActionResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=965,
  serialized_end=1005,
)

_MOBILITYACTION_ENUM.containing_type = _MOBILITYACTION
_MOBILITYCONFIG_CONFIGENTRY.containing_type = _MOBILITYCONFIG
_MOBILITYCONFIG.fields_by_name['config'].message_type = _MOBILITYCONFIG_CONFIGENTRY
_GETMOBILITYCONFIGSRESPONSE_CONFIGSENTRY.fields_by_name['value'].message_type = core_dot_api_dot_grpc_dot_common__pb2._MAPPEDCONFIG
_GETMOBILITYCONFIGSRESPONSE_CONFIGSENTRY.containing_type = _GETMOBILITYCONFIGSRESPONSE
_GETMOBILITYCONFIGSRESPONSE.fields_by_name['configs'].message_type = _GETMOBILITYCONFIGSRESPONSE_CONFIGSENTRY
_GETMOBILITYCONFIGRESPONSE_CONFIGENTRY.fields_by_name['value'].message_type = core_dot_api_dot_grpc_dot_common__pb2._CONFIGOPTION
_GETMOBILITYCONFIGRESPONSE_CONFIGENTRY.containing_type = _GETMOBILITYCONFIGRESPONSE
_GETMOBILITYCONFIGRESPONSE.fields_by_name['config'].message_type = _GETMOBILITYCONFIGRESPONSE_CONFIGENTRY
_SETMOBILITYCONFIGREQUEST.fields_by_name['mobility_config'].message_type = _MOBILITYCONFIG
_MOBILITYACTIONREQUEST.fields_by_name['action'].enum_type = _MOBILITYACTION_ENUM
DESCRIPTOR.message_types_by_name['MobilityAction'] = _MOBILITYACTION
DESCRIPTOR.message_types_by_name['MobilityConfig'] = _MOBILITYCONFIG
DESCRIPTOR.message_types_by_name['GetMobilityConfigsRequest'] = _GETMOBILITYCONFIGSREQUEST
DESCRIPTOR.message_types_by_name['GetMobilityConfigsResponse'] = _GETMOBILITYCONFIGSRESPONSE
DESCRIPTOR.message_types_by_name['GetMobilityConfigRequest'] = _GETMOBILITYCONFIGREQUEST
DESCRIPTOR.message_types_by_name['GetMobilityConfigResponse'] = _GETMOBILITYCONFIGRESPONSE
DESCRIPTOR.message_types_by_name['SetMobilityConfigRequest'] = _SETMOBILITYCONFIGREQUEST
DESCRIPTOR.message_types_by_name['SetMobilityConfigResponse'] = _SETMOBILITYCONFIGRESPONSE
DESCRIPTOR.message_types_by_name['MobilityActionRequest'] = _MOBILITYACTIONREQUEST
DESCRIPTOR.message_types_by_name['MobilityActionResponse'] = _MOBILITYACTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MobilityAction = _reflection.GeneratedProtocolMessageType('MobilityAction', (_message.Message,), {
  'DESCRIPTOR' : _MOBILITYACTION,
  '__module__' : 'core.api.grpc.mobility_pb2'
  # @@protoc_insertion_point(class_scope:mobility.MobilityAction)
  })
_sym_db.RegisterMessage(MobilityAction)

MobilityConfig = _reflection.GeneratedProtocolMessageType('MobilityConfig', (_message.Message,), {

  'ConfigEntry' : _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _MOBILITYCONFIG_CONFIGENTRY,
    '__module__' : 'core.api.grpc.mobility_pb2'
    # @@protoc_insertion_point(class_scope:mobility.MobilityConfig.ConfigEntry)
    })
  ,
  'DESCRIPTOR' : _MOBILITYCONFIG,
  '__module__' : 'core.api.grpc.mobility_pb2'
  # @@protoc_insertion_point(class_scope:mobility.MobilityConfig)
  })
_sym_db.RegisterMessage(MobilityConfig)
_sym_db.RegisterMessage(MobilityConfig.ConfigEntry)

GetMobilityConfigsRequest = _reflection.GeneratedProtocolMessageType('GetMobilityConfigsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMOBILITYCONFIGSREQUEST,
  '__module__' : 'core.api.grpc.mobility_pb2'
  # @@protoc_insertion_point(class_scope:mobility.GetMobilityConfigsRequest)
  })
_sym_db.RegisterMessage(GetMobilityConfigsRequest)

GetMobilityConfigsResponse = _reflection.GeneratedProtocolMessageType('GetMobilityConfigsResponse', (_message.Message,), {

  'ConfigsEntry' : _reflection.GeneratedProtocolMessageType('ConfigsEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETMOBILITYCONFIGSRESPONSE_CONFIGSENTRY,
    '__module__' : 'core.api.grpc.mobility_pb2'
    # @@protoc_insertion_point(class_scope:mobility.GetMobilityConfigsResponse.ConfigsEntry)
    })
  ,
  'DESCRIPTOR' : _GETMOBILITYCONFIGSRESPONSE,
  '__module__' : 'core.api.grpc.mobility_pb2'
  # @@protoc_insertion_point(class_scope:mobility.GetMobilityConfigsResponse)
  })
_sym_db.RegisterMessage(GetMobilityConfigsResponse)
_sym_db.RegisterMessage(GetMobilityConfigsResponse.ConfigsEntry)

GetMobilityConfigRequest = _reflection.GeneratedProtocolMessageType('GetMobilityConfigRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMOBILITYCONFIGREQUEST,
  '__module__' : 'core.api.grpc.mobility_pb2'
  # @@protoc_insertion_point(class_scope:mobility.GetMobilityConfigRequest)
  })
_sym_db.RegisterMessage(GetMobilityConfigRequest)

GetMobilityConfigResponse = _reflection.GeneratedProtocolMessageType('GetMobilityConfigResponse', (_message.Message,), {

  'ConfigEntry' : _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETMOBILITYCONFIGRESPONSE_CONFIGENTRY,
    '__module__' : 'core.api.grpc.mobility_pb2'
    # @@protoc_insertion_point(class_scope:mobility.GetMobilityConfigResponse.ConfigEntry)
    })
  ,
  'DESCRIPTOR' : _GETMOBILITYCONFIGRESPONSE,
  '__module__' : 'core.api.grpc.mobility_pb2'
  # @@protoc_insertion_point(class_scope:mobility.GetMobilityConfigResponse)
  })
_sym_db.RegisterMessage(GetMobilityConfigResponse)
_sym_db.RegisterMessage(GetMobilityConfigResponse.ConfigEntry)

SetMobilityConfigRequest = _reflection.GeneratedProtocolMessageType('SetMobilityConfigRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETMOBILITYCONFIGREQUEST,
  '__module__' : 'core.api.grpc.mobility_pb2'
  # @@protoc_insertion_point(class_scope:mobility.SetMobilityConfigRequest)
  })
_sym_db.RegisterMessage(SetMobilityConfigRequest)

SetMobilityConfigResponse = _reflection.GeneratedProtocolMessageType('SetMobilityConfigResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETMOBILITYCONFIGRESPONSE,
  '__module__' : 'core.api.grpc.mobility_pb2'
  # @@protoc_insertion_point(class_scope:mobility.SetMobilityConfigResponse)
  })
_sym_db.RegisterMessage(SetMobilityConfigResponse)

MobilityActionRequest = _reflection.GeneratedProtocolMessageType('MobilityActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOBILITYACTIONREQUEST,
  '__module__' : 'core.api.grpc.mobility_pb2'
  # @@protoc_insertion_point(class_scope:mobility.MobilityActionRequest)
  })
_sym_db.RegisterMessage(MobilityActionRequest)

MobilityActionResponse = _reflection.GeneratedProtocolMessageType('MobilityActionResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOBILITYACTIONRESPONSE,
  '__module__' : 'core.api.grpc.mobility_pb2'
  # @@protoc_insertion_point(class_scope:mobility.MobilityActionResponse)
  })
_sym_db.RegisterMessage(MobilityActionResponse)


_MOBILITYCONFIG_CONFIGENTRY._options = None
_GETMOBILITYCONFIGSRESPONSE_CONFIGSENTRY._options = None
_GETMOBILITYCONFIGRESPONSE_CONFIGENTRY._options = None
# @@protoc_insertion_point(module_scope)
