# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/api/grpc/wlan.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core.api.grpc import common_pb2 as core_dot_api_dot_grpc_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='core/api/grpc/wlan.proto',
  package='wlan',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x18\x63ore/api/grpc/wlan.proto\x12\x04wlan\x1a\x1a\x63ore/api/grpc/common.proto\"z\n\nWlanConfig\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12,\n\x06\x63onfig\x18\x02 \x03(\x0b\x32\x1c.wlan.WlanConfig.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"+\n\x15GetWlanConfigsRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\"\x9a\x01\n\x16GetWlanConfigsResponse\x12:\n\x07\x63onfigs\x18\x01 \x03(\x0b\x32).wlan.GetWlanConfigsResponse.ConfigsEntry\x1a\x44\n\x0c\x43onfigsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.common.MappedConfig:\x02\x38\x01\";\n\x14GetWlanConfigRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\"\x95\x01\n\x15GetWlanConfigResponse\x12\x37\n\x06\x63onfig\x18\x01 \x03(\x0b\x32\'.wlan.GetWlanConfigResponse.ConfigEntry\x1a\x43\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.common.ConfigOption:\x02\x38\x01\"Q\n\x14SetWlanConfigRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12%\n\x0bwlan_config\x18\x02 \x01(\x0b\x32\x10.wlan.WlanConfig\"\'\n\x15SetWlanConfigResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\"g\n\x0fWlanLinkRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x0c\n\x04wlan\x18\x02 \x01(\x05\x12\x10\n\x08node1_id\x18\x03 \x01(\x05\x12\x10\n\x08node2_id\x18\x04 \x01(\x05\x12\x0e\n\x06linked\x18\x05 \x01(\x08\"\"\n\x10WlanLinkResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x62\x06proto3'
  ,
  dependencies=[core_dot_api_dot_grpc_dot_common__pb2.DESCRIPTOR,])




_WLANCONFIG_CONFIGENTRY = _descriptor.Descriptor(
  name='ConfigEntry',
  full_name='wlan.WlanConfig.ConfigEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='wlan.WlanConfig.ConfigEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='wlan.WlanConfig.ConfigEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=184,
)

_WLANCONFIG = _descriptor.Descriptor(
  name='WlanConfig',
  full_name='wlan.WlanConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='wlan.WlanConfig.node_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='wlan.WlanConfig.config', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_WLANCONFIG_CONFIGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=184,
)


_GETWLANCONFIGSREQUEST = _descriptor.Descriptor(
  name='GetWlanConfigsRequest',
  full_name='wlan.GetWlanConfigsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='wlan.GetWlanConfigsRequest.session_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=229,
)


_GETWLANCONFIGSRESPONSE_CONFIGSENTRY = _descriptor.Descriptor(
  name='ConfigsEntry',
  full_name='wlan.GetWlanConfigsResponse.ConfigsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='wlan.GetWlanConfigsResponse.ConfigsEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='wlan.GetWlanConfigsResponse.ConfigsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=386,
)

_GETWLANCONFIGSRESPONSE = _descriptor.Descriptor(
  name='GetWlanConfigsResponse',
  full_name='wlan.GetWlanConfigsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='configs', full_name='wlan.GetWlanConfigsResponse.configs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETWLANCONFIGSRESPONSE_CONFIGSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=386,
)


_GETWLANCONFIGREQUEST = _descriptor.Descriptor(
  name='GetWlanConfigRequest',
  full_name='wlan.GetWlanConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='wlan.GetWlanConfigRequest.session_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='wlan.GetWlanConfigRequest.node_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=447,
)


_GETWLANCONFIGRESPONSE_CONFIGENTRY = _descriptor.Descriptor(
  name='ConfigEntry',
  full_name='wlan.GetWlanConfigResponse.ConfigEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='wlan.GetWlanConfigResponse.ConfigEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='wlan.GetWlanConfigResponse.ConfigEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=599,
)

_GETWLANCONFIGRESPONSE = _descriptor.Descriptor(
  name='GetWlanConfigResponse',
  full_name='wlan.GetWlanConfigResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='wlan.GetWlanConfigResponse.config', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETWLANCONFIGRESPONSE_CONFIGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=599,
)


_SETWLANCONFIGREQUEST = _descriptor.Descriptor(
  name='SetWlanConfigRequest',
  full_name='wlan.SetWlanConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='wlan.SetWlanConfigRequest.session_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wlan_config', full_name='wlan.SetWlanConfigRequest.wlan_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=601,
  serialized_end=682,
)


_SETWLANCONFIGRESPONSE = _descriptor.Descriptor(
  name='SetWlanConfigResponse',
  full_name='wlan.SetWlanConfigResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='wlan.SetWlanConfigResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=684,
  serialized_end=723,
)


_WLANLINKREQUEST = _descriptor.Descriptor(
  name='WlanLinkRequest',
  full_name='wlan.WlanLinkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='wlan.WlanLinkRequest.session_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wlan', full_name='wlan.WlanLinkRequest.wlan', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node1_id', full_name='wlan.WlanLinkRequest.node1_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node2_id', full_name='wlan.WlanLinkRequest.node2_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linked', full_name='wlan.WlanLinkRequest.linked', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=725,
  serialized_end=828,
)


_WLANLINKRESPONSE = _descriptor.Descriptor(
  name='WlanLinkResponse',
  full_name='wlan.WlanLinkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='wlan.WlanLinkResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=830,
  serialized_end=864,
)

_WLANCONFIG_CONFIGENTRY.containing_type = _WLANCONFIG
_WLANCONFIG.fields_by_name['config'].message_type = _WLANCONFIG_CONFIGENTRY
_GETWLANCONFIGSRESPONSE_CONFIGSENTRY.fields_by_name['value'].message_type = core_dot_api_dot_grpc_dot_common__pb2._MAPPEDCONFIG
_GETWLANCONFIGSRESPONSE_CONFIGSENTRY.containing_type = _GETWLANCONFIGSRESPONSE
_GETWLANCONFIGSRESPONSE.fields_by_name['configs'].message_type = _GETWLANCONFIGSRESPONSE_CONFIGSENTRY
_GETWLANCONFIGRESPONSE_CONFIGENTRY.fields_by_name['value'].message_type = core_dot_api_dot_grpc_dot_common__pb2._CONFIGOPTION
_GETWLANCONFIGRESPONSE_CONFIGENTRY.containing_type = _GETWLANCONFIGRESPONSE
_GETWLANCONFIGRESPONSE.fields_by_name['config'].message_type = _GETWLANCONFIGRESPONSE_CONFIGENTRY
_SETWLANCONFIGREQUEST.fields_by_name['wlan_config'].message_type = _WLANCONFIG
DESCRIPTOR.message_types_by_name['WlanConfig'] = _WLANCONFIG
DESCRIPTOR.message_types_by_name['GetWlanConfigsRequest'] = _GETWLANCONFIGSREQUEST
DESCRIPTOR.message_types_by_name['GetWlanConfigsResponse'] = _GETWLANCONFIGSRESPONSE
DESCRIPTOR.message_types_by_name['GetWlanConfigRequest'] = _GETWLANCONFIGREQUEST
DESCRIPTOR.message_types_by_name['GetWlanConfigResponse'] = _GETWLANCONFIGRESPONSE
DESCRIPTOR.message_types_by_name['SetWlanConfigRequest'] = _SETWLANCONFIGREQUEST
DESCRIPTOR.message_types_by_name['SetWlanConfigResponse'] = _SETWLANCONFIGRESPONSE
DESCRIPTOR.message_types_by_name['WlanLinkRequest'] = _WLANLINKREQUEST
DESCRIPTOR.message_types_by_name['WlanLinkResponse'] = _WLANLINKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WlanConfig = _reflection.GeneratedProtocolMessageType('WlanConfig', (_message.Message,), {

  'ConfigEntry' : _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _WLANCONFIG_CONFIGENTRY,
    '__module__' : 'core.api.grpc.wlan_pb2'
    # @@protoc_insertion_point(class_scope:wlan.WlanConfig.ConfigEntry)
    })
  ,
  'DESCRIPTOR' : _WLANCONFIG,
  '__module__' : 'core.api.grpc.wlan_pb2'
  # @@protoc_insertion_point(class_scope:wlan.WlanConfig)
  })
_sym_db.RegisterMessage(WlanConfig)
_sym_db.RegisterMessage(WlanConfig.ConfigEntry)

GetWlanConfigsRequest = _reflection.GeneratedProtocolMessageType('GetWlanConfigsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETWLANCONFIGSREQUEST,
  '__module__' : 'core.api.grpc.wlan_pb2'
  # @@protoc_insertion_point(class_scope:wlan.GetWlanConfigsRequest)
  })
_sym_db.RegisterMessage(GetWlanConfigsRequest)

GetWlanConfigsResponse = _reflection.GeneratedProtocolMessageType('GetWlanConfigsResponse', (_message.Message,), {

  'ConfigsEntry' : _reflection.GeneratedProtocolMessageType('ConfigsEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETWLANCONFIGSRESPONSE_CONFIGSENTRY,
    '__module__' : 'core.api.grpc.wlan_pb2'
    # @@protoc_insertion_point(class_scope:wlan.GetWlanConfigsResponse.ConfigsEntry)
    })
  ,
  'DESCRIPTOR' : _GETWLANCONFIGSRESPONSE,
  '__module__' : 'core.api.grpc.wlan_pb2'
  # @@protoc_insertion_point(class_scope:wlan.GetWlanConfigsResponse)
  })
_sym_db.RegisterMessage(GetWlanConfigsResponse)
_sym_db.RegisterMessage(GetWlanConfigsResponse.ConfigsEntry)

GetWlanConfigRequest = _reflection.GeneratedProtocolMessageType('GetWlanConfigRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETWLANCONFIGREQUEST,
  '__module__' : 'core.api.grpc.wlan_pb2'
  # @@protoc_insertion_point(class_scope:wlan.GetWlanConfigRequest)
  })
_sym_db.RegisterMessage(GetWlanConfigRequest)

GetWlanConfigResponse = _reflection.GeneratedProtocolMessageType('GetWlanConfigResponse', (_message.Message,), {

  'ConfigEntry' : _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETWLANCONFIGRESPONSE_CONFIGENTRY,
    '__module__' : 'core.api.grpc.wlan_pb2'
    # @@protoc_insertion_point(class_scope:wlan.GetWlanConfigResponse.ConfigEntry)
    })
  ,
  'DESCRIPTOR' : _GETWLANCONFIGRESPONSE,
  '__module__' : 'core.api.grpc.wlan_pb2'
  # @@protoc_insertion_point(class_scope:wlan.GetWlanConfigResponse)
  })
_sym_db.RegisterMessage(GetWlanConfigResponse)
_sym_db.RegisterMessage(GetWlanConfigResponse.ConfigEntry)

SetWlanConfigRequest = _reflection.GeneratedProtocolMessageType('SetWlanConfigRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETWLANCONFIGREQUEST,
  '__module__' : 'core.api.grpc.wlan_pb2'
  # @@protoc_insertion_point(class_scope:wlan.SetWlanConfigRequest)
  })
_sym_db.RegisterMessage(SetWlanConfigRequest)

SetWlanConfigResponse = _reflection.GeneratedProtocolMessageType('SetWlanConfigResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETWLANCONFIGRESPONSE,
  '__module__' : 'core.api.grpc.wlan_pb2'
  # @@protoc_insertion_point(class_scope:wlan.SetWlanConfigResponse)
  })
_sym_db.RegisterMessage(SetWlanConfigResponse)

WlanLinkRequest = _reflection.GeneratedProtocolMessageType('WlanLinkRequest', (_message.Message,), {
  'DESCRIPTOR' : _WLANLINKREQUEST,
  '__module__' : 'core.api.grpc.wlan_pb2'
  # @@protoc_insertion_point(class_scope:wlan.WlanLinkRequest)
  })
_sym_db.RegisterMessage(WlanLinkRequest)

WlanLinkResponse = _reflection.GeneratedProtocolMessageType('WlanLinkResponse', (_message.Message,), {
  'DESCRIPTOR' : _WLANLINKRESPONSE,
  '__module__' : 'core.api.grpc.wlan_pb2'
  # @@protoc_insertion_point(class_scope:wlan.WlanLinkResponse)
  })
_sym_db.RegisterMessage(WlanLinkResponse)


_WLANCONFIG_CONFIGENTRY._options = None
_GETWLANCONFIGSRESPONSE_CONFIGSENTRY._options = None
_GETWLANCONFIGRESPONSE_CONFIGENTRY._options = None
# @@protoc_insertion_point(module_scope)
